services:
  nginx:
    build: 
      context: ./nginx_service
    image: nginx_service:v1.6
    container_name: nginx_service
    ports:
      - "80:80"
      # - "443:443"
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - django
    volumes:
      - ./django_backend/static:/static
      - ./django_backend/media:/media
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  django:
    build: 
      context: ./django_backend 
    container_name: django_backend
    image: django_backend:v1.2
    ports:
      - "8001:8001"
    volumes:
      - ./django_backend:/app
    environment:
      AI_API_SERVER_HOST: 'model_api' # 'truong51972.ddns.net' if wanna deploy api server outside
      AI_API_SERVER_PORT: '8000'
    networks:
      - app-network

  model_api:
    build: 
      context: ./model_api 
    container_name: model_api
    image: model_api:v1.1
    ports:
      - "8000:8000"
    volumes:
      - ./model_api:/app
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    command: tunnel run
    restart: unless-stopped
    environment:
      - TUNNEL_TRANSPORT_PROTOCOL=quic
      - TUNNEL_ORIGIN_KEEPALIVE_TIMEOUT=30s
      - "TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}"
      - NO_AUTOUPDATE
    healthcheck:
      test: ["CMD", "cloudflared", "--version"]
      interval: 30s
      timeout: 10s
      retries: 7
      start_period: 10s
    networks:
      - app-network
      
#   mysql_database:
#     image: mysql:latest
#     container_name: mysql_database
#     environment:
#       MYSQL_ROOT_PASSWORD: 51972
#       MYSQL_DATABASE: LMS_database
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:

networks:
  app-network:
    driver: bridge