# Generated by Django 5.0.9 on 2024-10-01 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolled_course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer_option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='course.question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course.quiz'),
        ),
        migrations.AddField(
            model_name='student_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_answered', to='course.question'),
        ),
        migrations.AddField(
            model_name='student_answer',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_chose', to='course.answer_option'),
        ),
        migrations.AddField(
            model_name='ai_grading',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded_by_ai', to='course.student_answer'),
        ),
        migrations.AddField(
            model_name='student_quiz_attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempted_student', to='course.quiz'),
        ),
        migrations.AddField(
            model_name='student_quiz_attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempted_quiz', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_of_attempted_student', to='course.student_quiz_attempt'),
        ),
        migrations.AddField(
            model_name='sub_course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_courses', to='course.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='sub_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='course.sub_course'),
        ),
        migrations.AddField(
            model_name='module',
            name='sub_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='course.sub_course'),
        ),
        migrations.AddField(
            model_name='sub_module',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_modules', to='course.module'),
        ),
        migrations.AddField(
            model_name='sub_module_image',
            name='sub_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.sub_module'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolled_course',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='sub_course',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('order', 'sub_course')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('order', 'sub_course')},
        ),
        migrations.AlterUniqueTogether(
            name='sub_module',
            unique_together={('order', 'module')},
        ),
    ]
