# Generated by Django 5.0.9 on 2024-09-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='coursename',
            new_name='course_name',
        ),
    ]
