# Generated by Django 5.0.9 on 2024-09-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('order', 'course_content')},
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('order', 'course_content')},
        ),
    ]
