# Generated by Django 5.0.9 on 2024-09-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_coursename_course_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
