# Generated by Django 5.0.9 on 2024-09-25 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_lecture_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
