# Generated by Django 5.0.9 on 2024-09-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_lecture_created_at_lecture_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_content',
            new_name='Sub_Course',
        ),
    ]
