# Generated by Django 5.0.9 on 2024-10-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='mark_to_pass',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
