# Generated by Django 5.0.9 on 2024-09-26 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_course_content_sub_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_course',
            old_name='content_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='sub_course',
            old_name='content_title',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='sub_course',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sub_course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_courses', to='course.course'),
        ),
        migrations.AlterUniqueTogether(
            name='sub_course',
            unique_together={('course', 'order')},
        ),
    ]
