# Generated by Django 5.0.9 on 2024-09-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_rename_content_order_sub_course_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='course_content',
            new_name='sub_course',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='course_content',
            new_name='sub_course',
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('order', 'sub_course')},
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('order', 'sub_course')},
        ),
    ]
