# Generated by Django 5.0.9 on 2024-10-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_student_quiz_attempt_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_quiz_attempt',
            name='proctoring_data',
            field=models.JSONField(default={}, null=True),
        ),
    ]
