# Generated by Django 5.0.9 on 2024-09-26 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_rename_course_content_lecture_sub_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_created', to=settings.AUTH_USER_MODEL)),
                ('sub_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='course.sub_course')),
            ],
            options={
                'unique_together': {('order', 'sub_course')},
            },
        ),
        migrations.CreateModel(
            name='Sub_Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.TextField()),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_modules', to='course.module')),
            ],
            options={
                'unique_together': {('order', 'module')},
            },
        ),
        migrations.CreateModel(
            name='Sub_Module_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_html', models.TextField()),
                ('img', models.TextField()),
                ('sub_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='course.sub_module')),
            ],
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
    ]
