# Generated by Django 5.0.9 on 2024-09-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_module_sub_module_sub_module_content_delete_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='content',
        ),
    ]
