# Generated by Django 5.0.9 on 2024-09-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_module_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_module',
            name='content_html',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sub_module',
            name='img',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sub_module',
            name='video_url',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Sub_Module_Content',
        ),
    ]
