# Generated by Django 5.0.9 on 2024-10-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_quiz_time_limit_student_quiz_attempt_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_quiz_attempt',
            name='duration',
        ),
    ]
