# Generated by Django 5.0.9 on 2024-09-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_sub_module_content_html_sub_module_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_module',
            old_name='content_html',
            new_name='content_html_list',
        ),
        migrations.RenameField(
            model_name='sub_module',
            old_name='img',
            new_name='img_list',
        ),
    ]
