# Generated by Django 5.0.9 on 2024-09-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_rename_content_html_sub_module_content_html_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_module',
            old_name='img_list',
            new_name='image_list',
        ),
    ]
