# Generated by Django 5.0.9 on 2024-09-15 07:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='data_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
