# Generated by Django 5.0.9 on 2024-09-15 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_question_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='data_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
