# Generated by Django 5.0.9 on 2024-09-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_question_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
