# Generated by Django 5.0.9 on 2024-09-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_alter_question_data_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='data_created',
            new_name='created_at',
        ),
    ]
