# Generated by Django 5.1.1 on 2024-09-06 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_remove_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255, unique=True)),
                ('program_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='subject',
            field=models.ForeignKey(default=0.0005263157894736842, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='question_bank.subject'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrainingProgramSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.trainingprogram')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.subject')),
            ],
            options={
                'unique_together': {('program', 'subject')},
            },
        ),
    ]
