# Generated by Django 5.1.1 on 2024-09-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0003_trainingprogram_remove_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='program_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='program_name',
            field=models.CharField(max_length=100),
        ),
    ]
