# Generated by Django 5.1.1 on 2024-09-07 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_group', '0002_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='module_group.modulegroup'),
        ),
    ]
