# Generated by Django 5.0.9 on 2024-10-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_image_delete_sub_module_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_module',
            old_name='content',
            new_name='html_content',
        ),
    ]
