# Generated by Django 5.0.9 on 2024-10-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_student_quiz_attempt_proctoring_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_quiz_attempt',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
